// var names : string[] = ["Gauri","paddy","Angular"];
// console.log("first element",names[0]);
// console.log("all names",names);
// names[3]="pruthvi";
// console.log("all names",names);
// names[1]="Angualr MEAN";
// console.log("All names",names);
// console.log(names.length);
// var names = ["Gauri","10","true","3.14"];
// console.log("first element",names);
var arr = [10, 20, 30];
arr[3] = "Gauri";
console.log("array", arr);
